apiVersion: v1
kind: Service
metadata:
  name: flask-gpu-demo
  namespace: flask-gpu-demo
spec:
  selector:
    app: flask-gpu-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
