apiVersion: v1
kind: Service
metadata:
  name: flask-gpu-demo
  namespace: flask-gpu-demo
spec:
  selector:
    app: flask-gpu-demo
  ports:
  - name: 8080-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
